source 'https://supermarket.chef.io'

metadata

cookbook 'example', git: 'https://github.com/davidgiesberg/austindevops-2016-04.git', ref: '5bb182a569956590c720ccb5088d689a99fc9daa', rel: 'cookbooks/example'