name 'motdserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures motdserver'
long_description 'Installs/Configures motdserver'
version '3.0.0'

depends 'chef-vault'
depends 'example', '~> 3.0.0'
depends 'nginx', '= 2.7.6'
