name 'motdserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures motdserver'
long_description 'Installs/Configures motdserver'
version '0.1.0'

depends 'example', '= 2.0.0'
depends 'nginx', '= 2.7.6'
